### ISSUE TITLE
[Bug] Decoding errors

### ISSUE THREAD

**Issue by Kristinita** [apas/pastery#9]
### Summary

I can not begin use Pastery plugin.
### Expected behavior

Successful paste my code on Pastery and link to Pastery URL in my clipboard.
### Actual behavior

``` python
command: pastery {}
Trying to post with Python lib
Trying to post with CURL
Traceback (most recent call last):
  File "pastery in E:\Sublime Text 3\Data\Installed Packages\Pastery.sublime-package", line 23, in run
TypeError: string argument without an encoding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/json/decoder.py", line 367, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "pastery in E:\Sublime Text 3\Data\Installed Packages\Pastery.sublime-package", line 40, in run
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 369, in raw_decode
ValueError: No JSON object could be decoded
```
### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I log in in Pastery → I paste my API key in my `User\Pastery.sublime-settings` file. I select any code (tested on HTML, CSS and Python codes) → <kbd>Ctrl+Alt+C</kbd> → I get stack trace.
### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by skorokithakis** [comment]
@apas, can we take over maintenance of the project? We don't mind, and users would talk to us about fixing bugs.

**Comment by apas** [comment]
@skorokithakis that'd be alright. I can invite you & @stelabouras to the repo if you'd like.

**Comment by skorokithakis** [comment]
That would be great. Can we also have rights to submit to the Sublime Text directory? I'm not sure how that works, do you just push to this repo, or is there a process?

**Comment by apas** [comment]
@skorokithakis you can develop in master or in any other branch[, merge whenever you want in master,] and then create a release with a tag (follows strict vX.X.X naming convention) for master. Package Control will pick it up soon enough and upon ST relaunch will install update. I'm going to close the issue now, please be free to mail me directly for more.

**Comment by skorokithakis** [comment]
Fantastic, thanks.

**Comment by skorokithakis** [comment]
It turns out that all these issues had been fixed in #6, back in January, but a release hadn't been made. I tagged a new release and this should be okay now.

**Comment by apas** [comment]
@skorokithakis I've seen you pushed a new `v1.1.2` tag w/o a corresponding release and apparently it's picked up by PC and works. My local Pastery's updated. It's clear to me now that you _technically_ don't need a release per se, however I'd recommend doing both.

**Comment by skorokithakis** [comment]
Ah, yes, I meant to look into releasing but forgot. I made a release now, I didn't know if I needed to upload the binaries myself or if GitHub adds them, but it turns out all I needed to do was add the release title, thanks.

**Comment by Kristinita** [comment]
Now Pastery worked for me. Many thanks!
